### ISSUE TITLE
What is the data file looks like for the drawgraphs.py

### ISSUE THREAD

**Issue by ArchieGu** [nasa/WellClear#2]
Hi, I've been interested in the detect and avoid function for UAS, when I ran the code, I tried the `drawgraphs.py` but it required a data file. I don't know where the file is and what it should looked like. 

Could you please tell me how to create the data file? 
Thank you.

**Comment by cesaramh** [comment]
DAIDALUS is a library. The programs in Java/C++ that are provided are just examples of how to use the library. The scripts are for analysis of information provided by the library. See https://nasa.github.io/WellClear/ for information on how to use the scripts (see the advanced features section)

--
Cesar
